/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DAOCargo;
import dao.DAOCategoria;
import dao.DAOCliente;
import dao.DAOFornecedor;
import dao.DAOFuncionario;
import dao.DAOProduto;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author DAVI
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    DAOCargo daoCargo = new DAOCargo();
    DAOProduto daoProduto = new DAOProduto();
    DAOFuncionario daoFunc = new DAOFuncionario();
    DAOCategoria daoCat = new DAOCategoria();
    DAOFornecedor daoFornec = new DAOFornecedor();
    DAOCliente daoCliente = new DAOCliente();

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/oculos.png")));
    }

    public void habilitarMenus() {
        if (daoCat.getLista().isEmpty() || daoFornec.getLista().isEmpty()) {
            menuProdutos.setEnabled(false);
            menuProdutos.setToolTipText("Cadastre ao menos uma categoria e um fornecedor"
                    + " antes de cadastrar um produto!");
        } else {
            menuProdutos.setEnabled(true);
            menuProdutos.setToolTipText("Cadastro de produtos");
        }

        if (daoCargo.getLista().isEmpty()) {
            menuFuncionarios.setEnabled(false);
            menuFuncionarios.setToolTipText("Cadastre ao menos um cargo antes de cadastrar um funcionário!");
        } else {
            menuFuncionarios.setEnabled(true);
            menuFuncionarios.setToolTipText("Cadastro de funcionários");
        }

        if (daoProduto.getLista().isEmpty()
                || daoFunc.getListaVendedores().isEmpty() || daoCliente.getLista().isEmpty()) {
            menuVendas.setEnabled(false);
            menuVendas.setToolTipText("Cadastre ao menos um produto, um vendedor e um cliente "
                    + "antes de registrar uma venda!");

        } else {
            menuVendas.setEnabled(true);

            menuVendas.setToolTipText("Gerenciamento de Vendas");

        }

        if (daoProduto.getLista().isEmpty()) {
            menuCompras.setEnabled(false);
            menuCompras.setToolTipText("Cadastre ao menos um produto antes de registrar uma compra!");
        } else {
            menuCompras.setEnabled(true);
            menuCompras.setToolTipText("Gerenciamento de compras");

        }
    }

    public FormPrincipal() {
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
        habilitarMenus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenuItem();
        menuCargos = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        btnFechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Ótica");
        setResizable(false);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoOtica.png"))); // NOI18N

        menuCadastros.setText("Cadastros");

        menuClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.setToolTipText("Cadastro de Clientes");
        menuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuCadastros.add(menuClientes);

        menuFornecedores.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedor.png"))); // NOI18N
        menuFornecedores.setText("Fornecedores");
        menuFornecedores.setToolTipText("Cadastro de Fornecedores");
        menuFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedoresActionPerformed(evt);
            }
        });
        menuCadastros.add(menuFornecedores);

        menuCargos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cargos.png"))); // NOI18N
        menuCargos.setText("Cargos");
        menuCargos.setToolTipText("Cadastro de cargos de funcionário");
        menuCargos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCargosMouseEntered(evt);
            }
        });
        menuCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCargosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCargos);

        menuCategorias.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categoria.png"))); // NOI18N
        menuCategorias.setText("Categorias");
        menuCategorias.setToolTipText("Cadastro de categorias de produtos");
        menuCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCategoriasMouseEntered(evt);
            }
        });
        menuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriasActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCategorias);

        menuFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionarios.png"))); // NOI18N
        menuFuncionarios.setText("Funcionários");
        menuFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFuncionariosMouseEntered(evt);
            }
        });
        menuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuFuncionarios);

        menuProdutos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produto.png"))); // NOI18N
        menuProdutos.setText("Produtos");
        menuProdutos.setToolTipText("Produtoasasa");
        menuProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuProdutosMouseEntered(evt);
            }
        });
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuProdutos);

        barraMenu.add(menuCadastros);

        jMenu1.setText("Operações Financeiras");

        menuVendas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/venda.png"))); // NOI18N
        menuVendas.setText("Gerenciar Vendas");
        menuVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendasActionPerformed(evt);
            }
        });
        jMenu1.add(menuVendas);

        menuCompras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compra.png"))); // NOI18N
        menuCompras.setText("Gerenciar Compras");
        menuCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComprasActionPerformed(evt);
            }
        });
        jMenu1.add(menuCompras);

        barraMenu.add(jMenu1);

        menuAjuda.setText("Ajuda");

        menuSobre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        barraMenu.add(menuAjuda);

        menuSair.setText("Sair");

        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        menuSair.add(btnFechar);

        barraMenu.add(menuSair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sistema de Gerenciamento de Óticas desenvolvido "
                + "no curso Técnico \nem Informática do "
                + "Instituto Federal de Minas Gerais - Campus São \nJoão Evangelista.\n"
                + "Autor: Davi Martins Freitas de Oliveira Fonseca.",
                "Olá!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        // TODO add your handling code here:
        FormCliente form = new FormCliente(this, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Manutenção de Clientes");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);

    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedoresActionPerformed
        // TODO add your handling code here:
        FormFornecedores form = new FormFornecedores(this, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Manutenção de Fornecedores");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        habilitarMenus();
    }//GEN-LAST:event_menuFornecedoresActionPerformed

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        // TODO add your handling code here:
        FormProdutos form = new FormProdutos(this, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Manutenção de Produtos");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        habilitarMenus();
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void menuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosActionPerformed
        // TODO add your handling code here:
        FormFuncionario form = new FormFuncionario(this, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Manutenção de Funcionários");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        habilitarMenus();
    }//GEN-LAST:event_menuFuncionariosActionPerformed

    private void menuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendasActionPerformed
        // TODO add your handling code here:
        FormVendas form = new FormVendas(this, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Manutenção de Vendas");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_menuVendasActionPerformed

    private void menuCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargosActionPerformed
        // TODO add your handling code here:
        FormCargo form = new FormCargo(this, true);
        form.setTitle("Manutenção de Cargos de Funcionários");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        habilitarMenus();
    }//GEN-LAST:event_menuCargosActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void menuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriasActionPerformed
        // TODO add your handling code here:
        FormCategoria form = new FormCategoria(this, true);
        form.setTitle("Manutenção de Categorias de Produtos");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        habilitarMenus();

    }//GEN-LAST:event_menuCategoriasActionPerformed

    private void menuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComprasActionPerformed
        // TODO add your handling code here:
        FormCompras form = new FormCompras(this, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Manutenção de Compras");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_menuComprasActionPerformed

    private void menuProdutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProdutosMouseEntered
        // TODO add your handling code here:
        habilitarMenus();
    }//GEN-LAST:event_menuProdutosMouseEntered

    private void menuFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionariosMouseEntered
        // TODO add your handling code here:
        habilitarMenus();
    }//GEN-LAST:event_menuFuncionariosMouseEntered

    private void menuCategoriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoriasMouseEntered
        // TODO add your handling code here:
        habilitarMenus();
    }//GEN-LAST:event_menuCategoriasMouseEntered

    private void menuCargosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCargosMouseEntered
        // TODO add your handling code here:
        habilitarMenus();
    }//GEN-LAST:event_menuCargosMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPrincipal form = new FormPrincipal();
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }
        });
    }

    public JMenuItem getMenuFuncionarios() {
        return menuFuncionarios;
    }

    public void setMenuFuncionarios(JMenuItem menuFuncionarios) {
        this.menuFuncionarios = menuFuncionarios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem btnFechar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuCargos;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuCompras;
    private javax.swing.JMenuItem menuFornecedores;
    private javax.swing.JMenuItem menuFuncionarios;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenuItem menuVendas;
    // End of variables declaration//GEN-END:variables
}
